image: node:18
variables:
  NODE_OPTIONS: "--openssl-legacy-provider"
stages:
  - install
  - build
  - test
  - deploy

install:
  stage: install
  cache:
    paths:
      - node_modules/
    key: "$CI_COMMIT_REF_SLUG"
  script:
    - npm install
  artifacts:
    paths:
      - node_modules
    expire_in: 1 hour

firebase_build:
  stage: build
  script:
    - npm run build
  artifacts:
    paths:
      - build
    expire_in: 1 week
  only:
    - master

test:
  image: mcr.microsoft.com/playwright:v1.28.0-focal
  stage: test
  variables:
    NODE_OPTIONS: ""
  parallel: 10
  script:
    - npx playwright install --with-deps
    - npx playwright test --shard=$CI_NODE_INDEX/$CI_NODE_TOTAL
  artifacts:
    when: on_failure
    paths:
      - test-results
      - playwright-report
    expire_in: 1 hour

pages:
  stage: deploy
  script:
    - npm run build-dev
    - rm -rf public/
    - mv build/ public/
  artifacts:
    paths:
      - public
    expire_in: 1 week
  only:
    - dev

firebase_deploy:
  image: rambabusaravanan/firebase
  stage: deploy
  script:
    - firebase use koronis-scouting-system --token $FIREBASE_TOKEN
    - firebase deploy --only hosting -m "Pipe $CI_PIPELINE_ID Build $CI_BUILD_ID" --token $FIREBASE_TOKEN
  only:
    - master