firebase:
  image: rambabusaravanan/firebase
  stage: deploy
  cache:
    paths:
      - node_modules/
    key: "$CI_BUILD_REPO"
  script:
    - npm install
    - CI=false npm run build
    - firebase use koronis-scouting-system --token $FIREBASE_TOKEN
    - firebase deploy --only hosting -m "Pipe $CI_PIPELINE_ID Build $CI_BUILD_ID" --token $FIREBASE_TOKEN
  artifacts:
    paths:
      - build
  only:
    - master

pages:
  image: node:12.18.2-buster
  stage: deploy
  script:
    - rm -rf *
    - mkdir public
    - cd public
    - mkdir dev
    - cd ..
    - git clone -b dev https://gitlab.com/koronis-scouting-system/kss-client dev
    - cd dev
    - npm install
    - CI=false npm run devbuild
    - mv dev/build/* public/dev
  artifacts:
    paths:
      - public
  only:
    - master
    - dev
