firebase_build:
  image: node:18
  stage: build
  cache:
    paths:
      - node_modules/
    key: "$CI_BUILD_REPO"
  script:
    - npm install
    - CI=false npm run build
  artifacts:
    paths:
      - build
  only:
    - master

firebase:
  image: rambabusaravanan/firebase
  stage: deploy
  script:
    - firebase use koronis-scouting-system --token $FIREBASE_TOKEN
    - firebase deploy --only hosting -m "Pipe $CI_PIPELINE_ID Build $CI_BUILD_ID" --token $FIREBASE_TOKEN
  artifacts:
    paths:
      - build
  only:
    - master

pages:
  image: node:18
  stage: deploy
  script:
    - npm install
    - CI=false npm run devbuild
  artifacts:
    paths:
      - build
  only:
    - dev
