image: node:8.11.1

cache:
  paths:
    - dev/node_modules/
    - prod/node_modules/

pages:
  stage: deploy
  script:
    - rm -rf *
    - mkdir public
    - cd public
    - mkdir dev
    - mkdir latest
    - cd ..
    - git clone -b dev https://gitlab.com/koronis-scouting-system/kss-client dev
    - git clone -b master https://gitlab.com/koronis-scouting-system/kss-client prod
    - cd dev
    - npm install
    - CI=false npm run build
    - cd ../prod
    - npm install
    - CI=false npm run build
    - cd ..
    - mv dev/build public
    - cd public
    - mv build dev
    - cd ..
    - mv prod/build public
    - cd public
    - mv build latest
    - cd ..
  artifacts:
    paths:
      - public
  only:
    - master
    - dev
